<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>vn.edu.vnu.uet.group8</groupId>
  <artifactId>auction-system</artifactId>
  <version>1.0-SNAPSHOT</version>

  <packaging>pom</packaging>
    <name>auction-system-parent</name>
    <properties>
        <maven.compiler.source>25.0.2</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <modules>
        <module>auction-common</module>
        <module>auction-server</module>
        <module>auction-client</module>
    </modules>

</project>