package vn.edu.vnu.uet.group8.common.enums;

public enum SpecKey {
  // GENARAL
    CONDITION,
    BRAND,
    MODEL,
    COLOR,
    MATERIAL,
    WEIGHT_KG,
    COUNTRY_ORIGIN,
    QUANTITY,

  // ELECTRONICS
    WARRANTY_MONTHS, STORAGE_GB, RAM_GB,
    SCREEN_SIZE_INCH, BATTERY_WH, OS,

  // Thời trang
    SIZE, GENDER, STYLE,

  // Xe cộ
  VEHICLE_MAKE, VEHICLE_YEAR, MILEAGE_KM,
  ENGINE_CC, FUEL_TYPE, TRANSMISSION, LICENSE_PLATE_CITY,

  // Bất động sản
  AREA_M2, LAND_TYPE, FLOORS, BEDROOMS, BATHROOMS,
  LEGAL_STATUS, LOCATION_DISTRICT, LOCATION_CITY, FACING_DIRECTION,

  // Đồ cổ
  ERA, PROVENANCE, CERTIFICATE, RARITY,

  // WATCHES
  YEAR, ORIGIN, WARRANTY,

  // JEWELRY
  WEIGHT,

  // ART
  ARTIST, DIMENSIONS,

  // VEHICLES
  MILEAGE,

  // BOOKS
  AUTHOR, PUBLISHER,

  // ANTIQUES
  PERIOD
  
}
