name: Java CI with Maven

on:
  push:
    branches: [ "main" ] # Chạy khi push vào nhánh main
  pull_request:
    branches: [ "main" ] # Chạy khi tạo Pull Request vào main

jobs:
  build:
    runs-on: ubuntu-latest # Chạy trên máy ảo Linux

    steps:
    - uses: actions/checkout@v4 # Lấy code từ repo về máy ảo
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and Test with Maven
      run: mvn -B test # Lệnh chạy JUnit test tự động

# - name: Package Application
#       run: mvn package -DskipTests # Đóng gói thành file .jar

# - name: Upload Artifact
#   uses: actions/upload-artifact@v4
#   with:p
#     name: auction-app-binary
#     path: target/*.jar # Lưu file .jar lại để tải về